# dataset config
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: artist_id
NET_SOURCE_ID_FIELD: source_id
NET_TARGET_ID_FIELD: target_id
LABEL_FIELD: label
NEG_PREFIX: neg_
load_col:
  inter: [user_id, artist_id]
  net: [source_id, target_id]

# data filtering for interactions
#val_interval:
#    rating: "[3,inf)"
#unused_col:
#    inter: [rating]

user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

# social network config
filter_net_by_inter: True
undirected_net: True

# settings
reproducibility: True
seed: 2024

# training and evaluation
epochs: 5000
train_batch_size: 512
eval_batch_size: 51200000
valid_metric: NDCG@10
stopping_step: 50
warm_up_epochs: 100
embedding_size: 32
n_layers: 2
drop_ratio: 0.1
instance_cnt: 5
reg_weight: 1e-05
ssl_weight: 1e-05
ssl_tau: 0.1
learning_rate: 0.001